/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/join': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Exchange an access code for a session */
    post: operations['join_api_auth_join_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Who am I */
    get: operations['me_api_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a game (returns host and team codes) */
    post: operations['create_api_games_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Game overview; codes only for the host */
    get: operations['info_api_games__game_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/action-space': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** What my country may do this round */
    get: operations['action_space_api_games__game_id__action_space_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Events of a round, filtered by what I may see */
    get: operations['events_api_games__game_id__events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/log': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Full GameLog for replay and analytics (host) */
    get: operations['game_log_api_games__game_id__log_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/observation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** What my country sees */
    get: operations['observation_api_games__game_id__observation_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Submit (or replace) my orders */
    put: operations['submit_api_games__game_id__orders_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/replay': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Replay the log with the engine; [] = no divergence */
    get: operations['game_replay_api_games__game_id__replay_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/round': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Round status */
    get: operations['round_status_api_games__game_id__round_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/rounds/{number}/laugh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Pick the funniest team (host) */
    post: operations['laugh_api_games__game_id__rounds__number__laugh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/rounds/{number}/resolve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Resolve round `number` (host) */
    post: operations['resolve_api_games__game_id__rounds__number__resolve_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/{game_id}/state': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Full game state (host) */
    get: operations['state_api_games__game_id__state_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Available rules versions */
    get: operations['list_rules_api_rules_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rules/schema': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** JSON Schema of a rules file */
    get: operations['schema_api_rules_schema_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rules/{version}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Rules after extends, as the engine sees them */
    get: operations['get_rules_api_rules__version__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Process is alive */
    get: operations['healthz_healthz_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/readyz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Database reachable */
    get: operations['readyz_readyz_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ActionOption */
    ActionOption: {
      /**
       * Available
       * @default true
       */
      available: boolean
      /**
       * Cost
       * @default 0
       */
      cost: number
      /** Id */
      id: string
      /**
       * Max Count
       * @description Max units this round, if limited
       */
      max_count?: number | null
      /** Max Per Target */
      max_per_target?: number | null
      /** Min Amount */
      min_amount?: number | null
      /**
       * Reason
       * @description Why unavailable, if not available
       */
      reason?: string | null
      /** Requires */
      requires?: string | null
      /**
       * Targets
       * @description Allowed target ids, if targeted
       */
      targets?: string[] | null
      ui: components['schemas']['UiSpec']
    }
    /** ActionSpace */
    ActionSpace: {
      /** Actions */
      actions: {
        [key: string]: components['schemas']['ActionOption']
      }
      /** Budget */
      budget: number
      /** Country Id */
      country_id: string
      /** Round */
      round: number
    }
    /**
     * ActionSpec
     * @description One player action. Fields that do not apply to an action stay at their default.
     */
    ActionSpec: {
      /** Active */
      active?: ('same_round' | 'next_round') | null
      /**
       * Anonymous
       * @default false
       */
      anonymous: boolean
      /** Available */
      available?: ('same_round' | 'next_round') | null
      /**
       * Cost
       * @default 0
       */
      cost: number
      /** Duration Rounds */
      duration_rounds?: number | null
      /** Effect */
      effect?: {
        [key: string]: number
      }
      /** Max Per City Per Round */
      max_per_city_per_round?: number | null
      /** Max Per Round */
      max_per_round?: number | null
      /** Max Per Target City Per Round */
      max_per_target_city_per_round?: number | null
      /** Min Amount */
      min_amount?: number | null
      /**
       * Once Per Game
       * @default false
       */
      once_per_game: boolean
      /**
       * Requires
       * @description Prerequisite: action id or resource
       */
      requires?: string | null
      /** Target */
      target?: ('own_city' | 'foreign_city' | 'own_country' | 'foreign_country') | null
      ui: components['schemas']['UiSpec']
      /** Usable */
      usable?: ('same_round' | 'next_round') | null
      /**
       * Visible To Target
       * @default false
       */
      visible_to_target: boolean
    }
    /**
     * AidTransferred
     * @description ``actor`` sent ``amount`` to ``target``; it lands in the recipient's aid_pending.
     */
    AidTransferred: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Amount */
      amount: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'aid_transferred'
    }
    /** BombsProduced */
    BombsProduced: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Bombs Pending After */
      bombs_pending_after: number
      /** Count */
      count: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'bombs_produced'
    }
    /** BotSlot */
    BotSlot: {
      /** Bot */
      bot: string
      /** Country Id */
      country_id: string
    }
    /** BudgetSpent */
    BudgetSpent: {
      /** Action */
      action: string
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Amount */
      amount: number
      /** Budget After */
      budget_after: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'budget_spent'
    }
    /** City */
    City: {
      /**
       * Destroyed
       * @default false
       */
      destroyed: boolean
      /**
       * Development
       * @description Development in percent
       */
      development: number
      /** Id */
      id: string
      /**
       * Life Level
       * @description Life level in 1/100 of a percent
       * @default 0
       */
      life_level: number
      /** Name */
      name: string
      /**
       * Shield
       * @default false
       */
      shield: boolean
    }
    /** CityDestroyed */
    CityDestroyed: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Cause */
      cause: string
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'city_destroyed'
    }
    /** CityInvested */
    CityInvested: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Development After */
      development_after: number
      /** Development Before */
      development_before: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'city_invested'
    }
    /** Country */
    Country: {
      /**
       * Aid Pending
       * @description Aid received, credited next round
       * @default 0
       */
      aid_pending: number
      /**
       * Bombs
       * @description Bombs ready to use this round
       * @default 0
       */
      bombs: number
      /**
       * Bombs Pending
       * @description Produced this round, usable next
       * @default 0
       */
      bombs_pending: number
      /** Budget */
      budget: number
      /** Cities */
      cities: components['schemas']['City'][]
      /** Id */
      id: string
      /**
       * Laugh
       * @description Laugh coefficient, percentage points
       * @default 0
       */
      laugh: number
      /** Name */
      name: string
      /**
       * Nuclear Tech
       * @default false
       */
      nuclear_tech: boolean
      /** Sanctioned By */
      sanctioned_by?: string[]
    }
    /** CountryOrders */
    CountryOrders: {
      /**
       * Aid
       * @description Country id -> amount
       */
      aid?: {
        [key: string]: number
      }
      /**
       * Bombs
       * @default 0
       */
      bombs: number
      /**
       * Eco Programs
       * @default 0
       */
      eco_programs: number
      /**
       * Invest
       * @description Own city ids; repeat an id to invest several times
       */
      invest?: string[]
      /**
       * Nuclear Tech
       * @default false
       */
      nuclear_tech: boolean
      /**
       * Sanctions
       * @description Country ids
       */
      sanctions?: string[]
      /**
       * Shields
       * @description Own city ids
       */
      shields?: string[]
      /**
       * Strikes
       * @description Foreign city ids
       */
      strikes?: string[]
    }
    /**
     * CreateGame
     * @example {
     *       "bots": [
     *         {
     *           "bot": "aggressor",
     *           "country_id": "dprk"
     *         },
     *         {
     *           "bot": "economist",
     *           "country_id": "iran"
     *         }
     *       ],
     *       "mode": "playtest",
     *       "overrides": {},
     *       "rules": "v1.0",
     *       "scenario": "smolny",
     *       "seed": 1,
     *       "title": "Тестовая партия"
     *     }
     */
    CreateGame: {
      /** Bots */
      bots?: components['schemas']['BotSlot'][]
      /**
       * Mode
       * @default live
       */
      mode: string
      /**
       * Overrides
       * @description Deep-merged over the rules
       */
      overrides?: {
        [key: string]: unknown
      }
      /**
       * Rules
       * @default v1.0
       */
      rules: string
      /**
       * Scenario
       * @default smolny
       */
      scenario: string
      /**
       * Seed
       * @default 0
       */
      seed: number
      /**
       * Title
       * @default
       */
      title: string
    }
    /** Divergence */
    Divergence: {
      /** Path */
      path: string
      /** Recorded */
      recorded: unknown
      /** Replayed */
      replayed: unknown
      /** Round */
      round: number
    }
    /** EcologyChanged */
    EcologyChanged: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Cause */
      cause: string
      /** Delta */
      delta: number
      /** Ecology After */
      ecology_after: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'ecology_changed'
    }
    /** ForeignCityView */
    ForeignCityView: {
      /** Destroyed */
      destroyed: boolean
      /** Id */
      id: string
      /** Life Level */
      life_level: number
      /** Name */
      name: string
    }
    /** ForeignCountryView */
    ForeignCountryView: {
      /** Average Life Level */
      average_life_level: number
      /** Cities */
      cities: components['schemas']['ForeignCityView'][]
      /** Id */
      id: string
      /** Laugh */
      laugh: number
      /** Name */
      name: string
    }
    /** GameInfo */
    GameInfo: {
      /** Current Round */
      current_round: number
      /** Host Code */
      host_code?: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Mode */
      mode: string
      /** Phase */
      phase: string
      /** Players */
      players: components['schemas']['PlayerInfo'][]
      /** Rounds Total */
      rounds_total: number
      /** Rules Version */
      rules_version: string
      /** Scenario Id */
      scenario_id: string
      /** Seed */
      seed: number
      /** Status */
      status: string
      /** Title */
      title: string
    }
    /** GameLog */
    GameLog: {
      initial_state: components['schemas']['GameState']
      /**
       * Log Schema Version
       * @default 1
       */
      log_schema_version: number
      /** Rounds */
      rounds?: components['schemas']['RoundRecord'][]
      /** @description Full rules after extends, for reproducibility */
      rules_snapshot: components['schemas']['RuleSet']
      /** Rules Version */
      rules_version: string
      /** Scenario Id */
      scenario_id: string
      /** Seed */
      seed: number
    }
    /** GameState */
    GameState: {
      /** Countries */
      countries: components['schemas']['Country'][]
      /**
       * Ecology
       * @description World ecology in percent
       */
      ecology: number
      /**
       * Modules
       * @description State of v2/v3 modules keyed by module id
       */
      modules?: {
        [key: string]: {
          [key: string]: unknown
        }
      }
      /** Round */
      round: number
      /**
       * State Schema Version
       * @default 1
       */
      state_schema_version: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HostInput */
    HostInput: {
      /**
       * Laugh Winner
       * @description Country id chosen by the host
       */
      laugh_winner?: string | null
    }
    /**
     * IncomeCoefficients
     * @description income = (k_development x development + k_ecology x ecology) / 100.
     */
    IncomeCoefficients: {
      /** K Development */
      k_development: number
      /** K Ecology */
      k_ecology: number
    }
    /** IncomeCredited */
    IncomeCredited: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Amount */
      amount: number
      /** Budget After */
      budget_after: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'income_credited'
    }
    /** JoinRequest */
    JoinRequest: {
      /** Code */
      code: string
    }
    /** JoinResponse */
    JoinResponse: {
      principal: components['schemas']['Principal']
      /** Token */
      token: string
    }
    /**
     * LaughAwarded
     * @description The host named ``target`` the funniest team of the round.
     */
    LaughAwarded: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Bonus */
      bonus: number
      /** Laugh After */
      laugh_after: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'laugh_awarded'
    }
    /** LifeLevelComputed */
    LifeLevelComputed: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /**
       * Life Level
       * @description 1/100 of a percent
       */
      life_level: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'life_level_computed'
    }
    /**
     * LifeWeights
     * @description life_level x100 = development x w_d + ecology x w_e + laugh x w_l (all in percent).
     */
    LifeWeights: {
      /** Development */
      development: number
      /** Ecology */
      ecology: number
      /** Laugh */
      laugh: number
    }
    /**
     * NuclearStrike
     * @description A bomb launched by ``actor`` at city ``target``; ``observe`` hides the actor.
     */
    NuclearStrike: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /**
       * Outcome
       * @enum {string}
       */
      outcome: 'absorbed' | 'destroyed' | 'already_destroyed'
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'nuclear_strike'
    }
    /** Observation */
    Observation: {
      /** Ecology */
      ecology: number
      me: components['schemas']['OwnCountryView']
      /**
       * News
       * @description Events visible to this country
       */
      news?: (
        | components['schemas']['OrderRejected']
        | components['schemas']['BudgetSpent']
        | components['schemas']['CityInvested']
        | components['schemas']['EcologyChanged']
        | components['schemas']['LifeLevelComputed']
        | components['schemas']['IncomeCredited']
        | components['schemas']['AidTransferred']
        | components['schemas']['TechDeveloped']
        | components['schemas']['ShieldBuilt']
        | components['schemas']['BombsProduced']
        | components['schemas']['NuclearStrike']
        | components['schemas']['CityDestroyed']
        | components['schemas']['SanctionApplied']
        | components['schemas']['LaughAwarded']
        | components['schemas']['RoundEnded']
      )[]
      /** Others */
      others: components['schemas']['ForeignCountryView'][]
      /** Round */
      round: number
    }
    /** OrderBook */
    OrderBook: {
      host?: components['schemas']['HostInput']
      /**
       * Orders
       * @description Country id -> orders
       */
      orders?: {
        [key: string]: components['schemas']['CountryOrders']
      }
    }
    /** OrderRejected */
    OrderRejected: {
      /** Action */
      action: string
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Detail */
      detail?: {
        [key: string]: unknown
      }
      /** Reason */
      reason: string
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'order_rejected'
    }
    /** OwnCityView */
    OwnCityView: {
      /** Destroyed */
      destroyed: boolean
      /** Development */
      development: number
      /** Id */
      id: string
      /** Life Level */
      life_level: number
      /** Name */
      name: string
      /** Shield */
      shield: boolean
    }
    /** OwnCountryView */
    OwnCountryView: {
      /** Aid Pending */
      aid_pending: number
      /** Average Life Level */
      average_life_level: number
      /** Bombs */
      bombs: number
      /** Bombs Pending */
      bombs_pending: number
      /** Budget */
      budget: number
      /** Cities */
      cities: components['schemas']['OwnCityView'][]
      /** Id */
      id: string
      /** Laugh */
      laugh: number
      /** Name */
      name: string
      /** Nuclear Tech */
      nuclear_tech: boolean
      /** Sanctioned By */
      sanctioned_by: string[]
    }
    /** Params */
    Params: {
      /**
       * Budget Priority
       * @description Action ids in the order the budget is spent
       */
      budget_priority: string[]
      ecology: components['schemas']['Range']
      income: components['schemas']['IncomeCoefficients']
      /**
       * Laugh Bonus
       * @description Percentage points added to the laugh winner
       */
      laugh_bonus: number
      life_weights: components['schemas']['LifeWeights']
      /** Rounds */
      rounds: number
    }
    /** PlayerInfo */
    PlayerInfo: {
      /** Country Id */
      country_id: string
      /** Join Code */
      join_code?: string | null
      /** Joined */
      joined: boolean
      /** Kind */
      kind: string
      /** Name */
      name: string
    }
    /**
     * Principal
     * @description Who is calling: decoded from the JWT.
     */
    Principal: {
      /** Country Id */
      country_id?: string | null
      /**
       * Game Id
       * Format: uuid
       */
      game_id: string
      /**
       * Role
       * @enum {string}
       */
      role: 'host' | 'player'
    }
    /** Range */
    Range: {
      /** Max */
      max: number
      /** Min */
      min: number
    }
    /**
     * RoundEnded
     * @description Per-country wrap-up: pending bombs and aid released, sanctions reset.
     */
    RoundEnded: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Aid Credited */
      aid_credited: number
      /** Bombs Released */
      bombs_released: number
      /** Budget After */
      budget_after: number
      /** Round */
      round: number
      /** Sanctions Lifted */
      sanctions_lifted: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'round_ended'
    }
    /** RoundRecord */
    RoundRecord: {
      /** Events */
      events: (
        | components['schemas']['OrderRejected']
        | components['schemas']['BudgetSpent']
        | components['schemas']['CityInvested']
        | components['schemas']['EcologyChanged']
        | components['schemas']['LifeLevelComputed']
        | components['schemas']['IncomeCredited']
        | components['schemas']['AidTransferred']
        | components['schemas']['TechDeveloped']
        | components['schemas']['ShieldBuilt']
        | components['schemas']['BombsProduced']
        | components['schemas']['NuclearStrike']
        | components['schemas']['CityDestroyed']
        | components['schemas']['SanctionApplied']
        | components['schemas']['LaughAwarded']
        | components['schemas']['RoundEnded']
      )[]
      orders: components['schemas']['OrderBook']
      /** Round */
      round: number
      state_after: components['schemas']['GameState']
    }
    /** RoundResult */
    RoundResult: {
      /** Events */
      events: number
      /** Finished */
      finished: boolean
      /** Next Round */
      next_round: number | null
      /** Round */
      round: number
      /** Standings */
      standings: [string, number][]
    }
    /** RoundStatus */
    RoundStatus: {
      /** Laugh Winner */
      laugh_winner: string | null
      /** Phase */
      phase: string
      /** Round */
      round: number
      /** Status */
      status: string
      /** Submitted */
      submitted: {
        [key: string]: boolean
      }
    }
    /** RuleSet */
    RuleSet: {
      /** Actions */
      actions: {
        [key: string]: components['schemas']['ActionSpec']
      }
      /** Extends */
      extends?: string | null
      /** Modules */
      modules: string[]
      params: components['schemas']['Params']
      /** Pipeline */
      pipeline: string[]
      /** Version */
      version: string
    }
    /**
     * SanctionApplied
     * @description ``actor`` sanctions country ``target``: every alive city loses ``delta`` development.
     */
    SanctionApplied: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Delta */
      delta: number
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'sanction_applied'
    }
    /** ShieldBuilt */
    ShieldBuilt: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'shield_built'
    }
    /** TechDeveloped */
    TechDeveloped: {
      /**
       * Actor
       * @description Country id that caused the event
       */
      actor?: string | null
      /** Round */
      round: number
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Target
       * @description Country or city id affected
       */
      target?: string | null
      /** Tech */
      tech: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'tech_developed'
    }
    /** UiSpec */
    UiSpec: {
      /**
       * Description
       * @default
       */
      description: string
      /**
       * Emoji
       * @default
       */
      emoji: string
      /** Title */
      title: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  join_api_auth_join_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JoinResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Principal']
        }
      }
    }
  }
  create_api_games_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGame']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  info_api_games__game_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  action_space_api_games__game_id__action_space_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActionSpace']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  events_api_games__game_id__events_get: {
    parameters: {
      query: {
        round: number
      }
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': (
            | components['schemas']['OrderRejected']
            | components['schemas']['BudgetSpent']
            | components['schemas']['CityInvested']
            | components['schemas']['EcologyChanged']
            | components['schemas']['LifeLevelComputed']
            | components['schemas']['IncomeCredited']
            | components['schemas']['AidTransferred']
            | components['schemas']['TechDeveloped']
            | components['schemas']['ShieldBuilt']
            | components['schemas']['BombsProduced']
            | components['schemas']['NuclearStrike']
            | components['schemas']['CityDestroyed']
            | components['schemas']['SanctionApplied']
            | components['schemas']['LaughAwarded']
            | components['schemas']['RoundEnded']
          )[]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  game_log_api_games__game_id__log_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameLog']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  observation_api_games__game_id__observation_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Observation']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_api_games__game_id__orders_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CountryOrders']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  game_replay_api_games__game_id__replay_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Divergence'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  round_status_api_games__game_id__round_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoundStatus']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  laugh_api_games__game_id__rounds__number__laugh_post: {
    parameters: {
      query?: {
        country_id?: string | null
      }
      header?: never
      path: {
        game_id: string
        number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  resolve_api_games__game_id__rounds__number__resolve_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
        number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoundResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  state_api_games__game_id__state_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameState']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_rules_api_rules_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string[]
        }
      }
    }
  }
  schema_api_rules_schema_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  get_rules_api_rules__version__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        version: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RuleSet']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  healthz_healthz_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  readyz_readyz_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
